### ISSUE TITLE
Symlink causing a fatal error

### ISSUE THREAD

**Issue by devonblzx** [rene-hermenau/wp-staging#65]
We had a symlink in /var/www/html and this caused a fatal error for wp-staging at:

apps/Backend/Modules/Jobs/Scan.php:139

```php
            unset($directory[key($directory)]);
```

$directory is a string at this point.

**Comment by rene-hermenau** [comment]
Fixed https://github.com/rene-hermenau/wp-staging/commit/489701e98bd494118764a8bdb7985b98d95e37b6
